
drop synonym TAS_MEASUREMENT_POINT;
drop view TAS_MEASUREMENT_POINT_V;

create or replace synonym TAS_MEASUREMENT_POINT
  for tas.MEASUREMENT_POINT@TASD.AESO;

create or replace view TAS_MEASUREMENT_POINT_V
 as (SELECT MEASUREMENT_POINT_ID, 
			MP_ID, 
			ZONE_CODE, 
			MEASUREMENT_POINT_TYPE_CODE,
			MEASUREMENT_POINT_DESCR,
			MEASUREMENT_POINT_EFF,
			MEASUREMENT_POINT_EXP,
			PROGRAM_IN,
			PROJECT_IN,
			INCL_IN_POD_LSB
	FROM TAS_MEASUREMENT_POINT
);
