function ca_aeso_ltlf_Ltlf(){var l='',B='" for "gwt:onLoadErrorFn"',z='" for "gwt:onPropertyErrorFn"',dc='"><\/script>',n='/',mb='219E918B2FF1AEEC21264CCCAF91EF2A.cache.html',kb='4567937DDC02FD578EAB7DF48A13799C.cache.html',lb='9AA056FA9937499248D7CD38277C1B28.cache.html',cc='<script id="',Cb='<script language="javascript" src="',ac="<script>ca_aeso_ltlf_Ltlf.onInjectionDone('ca.aeso.ltlf.Ltlf')<\/script>",v='=',jb='A7C8EED4ECB80EEFA10F339E14153472.cache.html',ib='AE116B770AFF945D74F89C146D96187E.cache.html',y='Bad handler "',wb='DOMContentLoaded',ob='GwtExt.css',ec='SCRIPT',bc='__gwt_marker_ca.aeso.ltlf.Ltlf',o='base',m='ca.aeso.ltlf.Ltlf',q='clear.cache.gif',u='content',db='gecko',eb='gecko1_8',nb='gwt.hybrid',A='gwt:onLoadErrorFn',w='gwt:onPropertyErrorFn',t='gwt:property',tb='head',hb='hosted.html?ca_aeso_ltlf_Ltlf',sb='href',bb='ie6',xb='iframe',p='img',zb="javascript:''",Bb='js/ext/adapter/ext/ext-base.js',Db='js/ext/adapter/ext/ext-base.js"><\/script>',Eb='js/ext/ext-all.js',Fb='js/ext/ext-all.js"><\/script>',ub='js/ext/resources/css/ext-all.css',vb='js/ext/resources/css/xtheme-gray.css',pb='link',r='meta',gb='moduleRequested',ab='msie',s='name',D='opera',Ab='position:absolute;width:0;height:0;border:none',qb='rel',F='safari',yb='selectionDone',cb='selectionStart',x='startup',rb='stylesheet',fb='unknown',C='user.agent',E='webkit';var gc=window,k=document,oc=gc.external,fc=gc.__gwtstatsEvent?function(a,b,c,d){gc.__gwtstatsEvent(a,b,c,d)}:null,Bc,rc,lc,kc=l,uc={},Ec=[],Ac=[],jc=[],xc,zc;fc&&fc(m,x,cb,{millis:(new Date()).getTime()});if(!gc.__gwt_stylesLoaded){gc.__gwt_stylesLoaded={}}if(!gc.__gwt_scriptsLoaded){gc.__gwt_scriptsLoaded={}}function qc(){try{return oc&&(oc.gwtOnLoad&&gc.location.search.indexOf(nb)==-1)}catch(a){return false}}
function tc(){if(Bc&&rc){var c=k.getElementById(m);var b=c.contentWindow;b.__gwt_initHandlers=ca_aeso_ltlf_Ltlf.__gwt_initHandlers;if(qc()){b.__gwt_getProperty=function(a){return mc(a)}}ca_aeso_ltlf_Ltlf=null;b.gwtOnLoad(xc,m,kc);fc&&fc(m,x,yb,{millis:(new Date()).getTime()})}}
function nc(){var j,h=bc,i;k.write(cc+h+dc);i=k.getElementById(h);j=i&&i.previousSibling;while(j&&j.tagName!=ec){j=j.previousSibling}function d(b){var a=b.lastIndexOf(n);return a>=0?b.substring(0,a+1):l}
;if(j&&j.src){kc=d(j.src)}if(kc==l){var c=k.getElementsByTagName(o);if(c.length>0){kc=c[c.length-1].href}else{var g=k.location;var e=g.href;kc=d(e.substr(0,e.length-g.hash.length))}}else if(kc.match(/^\w+:\/\//)){}else{var f=k.createElement(p);f.src=kc+q;kc=d(f.src)}if(i){i.parentNode.removeChild(i)}}
function yc(){var f=document.getElementsByTagName(r);for(var d=0,g=f.length;d<g;++d){var e=f[d],h=e.getAttribute(s),b;if(h){if(h==t){b=e.getAttribute(u);if(b){var i,c=b.indexOf(v);if(c>=0){h=b.substring(0,c);i=b.substring(c+1)}else{h=b;i=l}uc[h]=i}}else if(h==w){b=e.getAttribute(u);if(b){try{zc=eval(b)}catch(a){alert(y+b+z)}}}else if(h==A){b=e.getAttribute(u);if(b){try{xc=eval(b)}catch(a){alert(y+b+B)}}}}}}
function Dc(d,e){var a=jc;for(var b=0,c=d.length-1;b<c;++b){a=a[d[b]]||(a[d[b]]=[])}a[d[c]]=e}
function mc(d){var e=Ac[d](),b=Ec[d];if(e in b){return e}var a=[];for(var c in b){a[b[c]]=c}if(zc){zc(d,a,e)}throw null}
Ac[C]=function(){var d=navigator.userAgent.toLowerCase();var b=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(d.indexOf(D)!=-1){return D}else if(d.indexOf(E)!=-1){return F}else if(d.indexOf(ab)!=-1){var c=/msie ([0-9]+)\.([0-9]+)/.exec(d);if(c&&c.length==3){if(b(c)>=6000){return bb}}}else if(d.indexOf(db)!=-1){var c=/rv:([0-9]+)\.([0-9]+)/.exec(d);if(c&&c.length==3){if(b(c)>=1008)return eb}return db}return fb};Ec[C]={gecko:0,gecko1_8:1,ie6:2,opera:3,safari:4};ca_aeso_ltlf_Ltlf.onInjectionDone=function(){Bc=true;fc&&fc(m,x,gb,{millis:(new Date()).getTime()});tc()};ca_aeso_ltlf_Ltlf.onScriptLoad=function(){if(pc){rc=true;tc()}};nc();yc();var Cc;if(qc()){Cc=hb}else{try{Dc([bb],ib);Dc([D],jb);Dc([db],kb);Dc([eb],lb);Dc([F],mb);Cc=jc[mc(C)]}catch(a){return}}var wc;function vc(){if(!lc){lc=true;if(!__gwt_stylesLoaded[ob]){var a=k.createElement(pb);__gwt_stylesLoaded[ob]=a;a.setAttribute(qb,rb);a.setAttribute(sb,kc+ob);k.getElementsByTagName(tb)[0].appendChild(a)}if(!__gwt_stylesLoaded[ub]){var a=k.createElement(pb);__gwt_stylesLoaded[ub]=a;a.setAttribute(qb,rb);a.setAttribute(sb,kc+ub);k.getElementsByTagName(tb)[0].appendChild(a)}if(!__gwt_stylesLoaded[vb]){var a=k.createElement(pb);__gwt_stylesLoaded[vb]=a;a.setAttribute(qb,rb);a.setAttribute(sb,kc+vb);k.getElementsByTagName(tb)[0].appendChild(a)}tc();if(k.removeEventListener){k.removeEventListener(wb,vc,false)}if(wc){clearInterval(wc)}}}
var pc;function sc(){if(!pc){pc=true;var a=k.createElement(xb);a.src=zb;a.id=m;a.style.cssText=Ab;a.tabIndex=-1;k.body.appendChild(a);a.contentWindow.location.replace(kc+Cc)}}
if(k.addEventListener){k.addEventListener(wb,function(){sc();vc()},false)}var wc=setInterval(function(){if(/loaded|complete/.test(k.readyState)){sc();vc()}},50);if(!__gwt_scriptsLoaded[Bb]){__gwt_scriptsLoaded[Bb]=true;document.write(Cb+kc+Db)}if(!__gwt_scriptsLoaded[Eb]){__gwt_scriptsLoaded[Eb]=true;document.write(Cb+kc+Fb)}k.write(ac)}
ca_aeso_ltlf_Ltlf.__gwt_initHandlers=function(i,e,j){var d=window,g=d.onresize,f=d.onbeforeunload,h=d.onunload;d.onresize=function(a){try{i()}finally{g&&g(a)}};d.onbeforeunload=function(a){var c,b;try{c=e()}finally{b=f&&f(a)}if(c!=null){return c}if(b!=null){return b}};d.onunload=function(a){try{j()}finally{h&&h(a)}}};ca_aeso_ltlf_Ltlf();